Add big-int
nyuichi/satysfi-base pull request #198
Opened 2022-01-28 11:04 UTC by puripuri2100

2022-01-30 01:01 UTC, zeptometer requested changes

2022-01-30 01:10 UTC, zeptometer requested changes

2022-01-30 01:10 UTC, zeptometer commented on src/big-int.satyg
> +  type t = (bool * (int list))
大体想像はつくんですが、内部表現について実例含んだ解説コメントがあると嬉しいです。特に下の位の数がリストの先頭か末尾のどちら側に来るかみたいな話を書いてくれているとわかりやすいです。

2022-01-30 09:31 UTC, puripuri2100 commented on src/big-int.satyg
> +  type t = (bool * (int list))
確かにそうですね
コメントを追加しておきます

2022-01-30 09:32 UTC, puripuri2100 commented on src/big-int.satyg
> +  val zero : t
intの上限値を超える数に対してto-intをしたときの挙動は未定義、として実装してみます

2022-01-30 09:34 UTC, puripuri2100 commented on src/big-int.satyg
> +module BigInt : sig
`max-value` と `min-value` の定義はどうするべきなのでしょう
Intでは `2^63 - 1` と `-2^63 + 1` で定義できていますが、任意精度整数なので定義しようがなさそうな気がします

2022-01-30 10:24 UTC, zeptometer commented on src/big-int.satyg
> +module BigInt : sig
あ、その通りで定義しようがないので `bitsize`, `max-value`, `min-value` をBigIntで提供する必要はないと思う、という主旨の発言でした↓

> Int にあるけど BigInt に必要なさそうなのは `bitsize`, `max-value`, `min-value` くらいですかね。

2022-01-30 10:26 UTC, zeptometer commented on src/big-int.satyg
> +  val zero : t
その挙動でよいと思います 👍

2022-01-30 11:12 UTC, puripuri2100 commented on src/big-int.satyg
> +module BigInt : sig
完全に誤読していました
すみません

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +  let carry-and-fix (is-plus, lst) =
あーなるほど、これって数を10進表記にした時の各桁の数字をリストとして表してるんですね。
各要素をN bitの符号なし整数として表現した方が、計算速度が上がるのとビット演算が実装しやすくなるのとで好ましいと思います。2^N進数として表記した時の各桁の数字をリストにする感じになるので実装の基本的な方針は代わらないはず。OCamlの整数型は63bitだったはずなのでキャリーとかの計算しやすさを考えるとN=62にするのがよさそう。

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +  let carry-and-fix (is-plus, lst) =
ただ今ちゃんと動いてる時点でめちゃくちゃ偉いし、あまり一つのコードレビューを長くしたくないので。一旦このままの実装でmergeしてしまってもいいかなと思います。この実装でビット演算を実装するのはキツいと思うのでビット演算はなしで大丈夫です！

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +module BigInt : sig
別のコメントで指摘してるんですけど、ビット演算はしんどそうなので(少なくとも今回のPRでは)実装しなくて大丈夫ですー

2022-01-30 11:38 UTC, zeptometer commented on __test__/satysrc/generic.saty
> +let () = BigInt.((BigInt.of-string `42`) < (BigInt.of-string `136`)) |> Bool.to-string |> Debug.log in
`BigInt.ord` の実装について色々なケースをテストしたいですね。
```
let ord-to-string o = match o with | LT -> "LT" | GT -> "GT" | EQ -> "EQ" in
let () = (BigInt.of-string `333`) |> BigInt.compare  (BigInt.of-string `444`) |> ord-to-string |> Debug.log
```
みたいな感じですかね(この通りに実装して、というわけではないです)。

実装の分岐を見た感じ以下のテストケースがあると大体大丈夫そうかなと自信が持てそう。

* 123 -456 (符号が違う1)
* -123 456 (符号が違う2)
* 333  333 (同じ数1)
* -333 -333 (同じ数2)
* 1234 432 (長さが違う数1)
* 432 1234 (長さが違う数2)
* -1234 -432 (長さが違う数3)
* -432 -1234 (長さが違う数4)
* 332 333 (長さが同じ数1)
* 333 332 (長さが同じ数2)
* -332 -333 (長さが同じ数3)
* -333 -332 (長さが同じ数4)

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +      | x::xs when Int.(0x0029 < x) && Int.(x < 0x003A) -> (
これが `'0'-'9'` を表してるのは文脈上明らかなんですけど、一応コメントにそう書いておいてくれると嬉しいです。

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +    | 0x002D::xs -> sub xs [] |> Option.map (fun lst -> (false, lst))
こちらの 0x002D についても同じく。

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +  let of-string-opt str =
これって `str` が空文字列の時大丈夫です？(SATySFiって空文字列作れるんでしたっけ)

2022-01-30 11:38 UTC, zeptometer commented on src/big-int.satyg
> +    let (b, lst) = t in
(あまり重要でない点) `b` に `is-positive` のような名前をつけてくれるとコードが読み安くなって嬉しいです。

2022-01-30 13:26 UTC, puripuri2100 commented on src/big-int.satyg
> +  let of-string-opt str =
現状の実装だと空文字列は0になりますね
panicさせてます

2022-01-30 13:34 UTC, puripuri2100 commented on src/big-int.satyg
> +          | (_, []) -> Gt
逆に、リストの長さによる分岐をせずに `sub` にそのままリストを与えて比較させてしまう方が一貫性があるので良い気がしました

2022-01-30 13:34 UTC, puripuri2100 commented on src/big-int.satyg
> +  let of-string-opt str =
`of-string-opt` なのでpanicではなくて `None` ですね

2022-02-04 13:59 UTC, puripuri2100 commented on src/big-int.satyg
> +  let of-string-opt str =
修正しました

2022-02-04 13:59 UTC, puripuri2100 commented on src/big-int.satyg
> +    | 0x002D::xs -> sub xs [] |> Option.map (fun lst -> (false, lst))
コメント追加しました

2022-02-04 14:00 UTC, puripuri2100 commented on src/big-int.satyg
> +      | x::xs when Int.(0x0029 < x) && Int.(x < 0x003A) -> (
コメント追加しました

2022-02-04 14:00 UTC, puripuri2100 commented on src/big-int.satyg
> +  type t = (bool * (int list))
コメントと例を追加しておきました

2022-02-04 14:00 UTC, puripuri2100 commented on src/big-int.satyg
> +  val zero : t
実装しました

2022-02-04 14:17 UTC, puripuri2100 commented on __test__/satysrc/generic.saty
> +let () = BigInt.((BigInt.of-string `42`) < (BigInt.of-string `136`)) |> Bool.to-string |> Debug.log in
テストケースを追加しました

2022-02-04 14:17 UTC, puripuri2100 commented on src/big-int.satyg
> +          | (_, []) -> Gt
panicさせることにしました

2022-02-04 14:19 UTC, puripuri2100 commented on src/big-int.satyg
> +module BigInt : sig
Intモジュールで提供している関数を大体提供できた気がします

2023-03-21 02:00 UTC, puripuri2100 commented
かなり遅くなりましたが、指摘点修正しました

2023-04-19 09:47 UTC, zeptometer approved these changes
マージしちゃってよいと思います、お疲れさまでした 👍

2023-04-19 09:48 UTC, merged

2023-04-19 09:49 UTC, puripuri2100 commented
ありがとうございます🙏